### ISSUE TITLE
Incorrect sizing of blog post cover image

### ISSUE THREAD

**Issue by 05akalan57** [nextone0/nextone.dev#6]
![image](https://user-images.githubusercontent.com/70916256/197362058-80c9028e-7da2-4e53-9754-badd3a88a776.png)

**Possible fix suggestion;**
- Adjust pictures to manual height

**Comment by MuhammedErdogan05** [comment]
File Location | Corrected Code
--- | ---
![image-2](https://user-images.githubusercontent.com/96001424/197728954-d80acb33-2528-4552-b631-5bc4a42d3074.png) | ![Frame 5 (1)](https://user-images.githubusercontent.com/96001424/197745423-32c32617-b48f-4db2-827d-108df669fe01.png)

**Corrected piece of code**
-Fixed the issue as a result of correcting the sizing in the "css" part.
